### ISSUE TITLE
Libarchive is broken for toolchain linux

### ISSUE THREAD

**Issue by mariusvniekerk** [conda-forge/libarchive-feedstock#20]
https://anaconda.org/conda-forge/libarchive/3.3.3/download/linux-64/libarchive-3.3.3-h40d5236_1.tar.bz2

```
#!/bin/bash -eo pipefail
cd cf-graph
conda-forge-tick --run 4
Traceback (most recent call last):
  File "/opt/conda/bin/conda-forge-tick", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/root/repo/cf-scripts/scripts/conda-forge-tick", line 2, in <module>
    from conda_forge_tick.cli import main
  File "/root/repo/cf-scripts/conda_forge_tick/cli.xsh", line 9, in <module>
    from .auto_tick import main as main3
  File "/root/repo/cf-scripts/conda_forge_tick/auto_tick.xsh", line 23, in <module>
    from .migrators import *
  File "/root/repo/cf-scripts/conda_forge_tick/migrators.xsh", line 14, in <module>
    from conda_smithy.configure_feedstock import get_cfp_file_path
  File "/opt/conda/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 13, in <module>
    import conda_build.api
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 22, in <module>
    from conda_build.config import Config, get_or_merge_config, DEFAULT_PREFIX_LENGTH as _prefix_length
  File "/opt/conda/lib/python3.6/site-packages/conda_build/config.py", line 17, in <module>
    from .variants import get_default_variant
  File "/opt/conda/lib/python3.6/site-packages/conda_build/variants.py", line 15, in <module>
    from conda_build.utils import ensure_list, trim_empty_keys, get_logger
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 10, in <module>
    import libarchive
  File "/opt/conda/lib/python3.6/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/opt/conda/lib/python3.6/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/opt/conda/lib/python3.6/site-packages/libarchive/ffi.py", line 108, in <module>
    errno = ffi('errno', [c_archive_p], c_int)
  File "/opt/conda/lib/python3.6/site-packages/libarchive/ffi.py", line 95, in ffi
    f = getattr(libarchive, 'archive_'+name)
  File "/opt/conda/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/opt/conda/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /opt/conda/bin/python: undefined symbol: archive_errno
Exited with code 1
```

**Comment by mariusvniekerk** [comment]
Marked linux64 and osx64 as broken

**Comment by ocefpaf** [comment]
Argh :-/

I'll pull the package until we figure out what is going on. Thanks for reporting.

**Comment by ocefpaf** [comment]
> Marked linux64 and osx64 as broken

You were faster :smile:

**Comment by mingwandroid** [comment]
Could it maybe be an incompatibility between `python-libarchive-c` built against an older `libarchive`? Were they build in the right order (I believe at build-time `python-libarchive-c` might detect the symbols it finds in `libarchive`).

Are we pinning to 3.3.3 anywhere?

**Comment by ocefpaf** [comment]
That could be it. I don't think those are pinned.

**Comment by mariusvniekerk** [comment]
seems to be `python-libarchive-c` doing bad find_library_things

**Comment by mingwandroid** [comment]
Does your python 3.6 build include https://github.com/conda-forge/python-feedstock/blob/3.6/recipe/0015-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
?

**Comment by mariusvniekerk** [comment]
yes

**Comment by mariusvniekerk** [comment]
Issue seems to be 
```
>>> _findLib_prefix('archive')
'/opt/conda/lib/libarchive.so'
>>> _get_soname(_findLib_prefix('archive'))
None
```

After that it just returns None

**Comment by mariusvniekerk** [comment]
in _get_soname we make the assumption that 

```
            objdump = shutil.which('objdump')
            if not objdump:
                # objdump is not available, give up
                return None
```
In a simple miniconda case this fails there.

**Comment by mariusvniekerk** [comment]
This is provided by `binutils`

**Comment by mingwandroid** [comment]
Why do we need a separate binutils (we already got one)? I can fix this in Python rather than forcing this heavy dependency. Though technically this is an upstream issue with Python itself.

**Comment by mingwandroid** [comment]
OK, I have something that'll address this in a minimal way, the breakage is my fault. I guess I never run on computers without objdump!

**Comment by jakirkham** [comment]
Should this be closed? Looks like most of the discussion is about `python-libarchive-c`, which this is not.

**Comment by ocefpaf** [comment]
@mariusvniekerk I don't think we care about this anymore, right? Please re-open if I'm mistaken.
