### ISSUE TITLE
libarchive not installing from conda-forge repo on win-64

### ISSUE THREAD

**Issue by TimoRoth** [conda-forge/libarchive-feedstock#21]
We are using appveyor as Windows CI environment, and since a while, we are getting the following error right after setting up the environment:

```
[00:00:00] Build started
[00:00:00] git clone -q --branch=master https://github.com/OGGM/OGGM-Anaconda.git C:\projects\oggm-anaconda
[00:00:03] git checkout -qf 00af51e4f58b2e42ffb10ae44264689e96c3ebbb
[00:00:03] Running Install scripts
[00:00:03] powershell ./ci/install_miniconda.ps1
[00:00:04] Installing Python 3.6 for 64 bit architecture to C:\Python36-conda64
[00:00:04] Downloading Miniconda3-latest-Windows-x86_64.exe from http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe
[00:00:04] File saved at C:\projects\oggm-anaconda\Miniconda3-latest-Windows-x86_64.exe
[00:00:04] Installing C:\projects\oggm-anaconda\Miniconda3-latest-Windows-x86_64.exe to C:\Python36-conda64
[00:00:04] C:\projects\oggm-anaconda\Miniconda3-latest-Windows-x86_64.exe /S /D=C:\Python36-conda64
[00:00:07] 
[00:00:07] Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName          
[00:00:07] -------  ------    -----      -----     ------     --  -- -----------          
[00:00:07]       3       2      668        672       0.00   3032   1 Miniconda3-latest-...
[00:01:13] Python 3.6 (64) installation complete
[00:01:13] pip already installed.
[00:01:13] 
[00:01:13] 
[00:01:13] SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
[00:01:13] python --version
[00:01:13] Python 3.7.0
[00:01:13] python -c "import struct; print(struct.calcsize('P') * 8)"
[00:01:13] 64
[00:01:13] conda config --set always_yes yes --set changeps1 no
[00:01:14] conda config --prepend channels conda-forge
[00:01:14] conda config --set anaconda_upload no
[00:01:14] conda update -q --all
[00:01:38] Solving environment: ...working... done
[00:02:07] 
[00:02:07] ## Package Plan ##
[00:02:07] 
[00:02:07]   environment location: C:\Python36-conda64
[00:02:07] 
[00:02:07] 
[00:02:07] The following packages will be downloaded:
[00:02:07] 
[00:02:07]     package                    |            build
[00:02:07]     ---------------------------|-----------------
[00:02:07]     yaml-0.1.7                 |           vc14_0         103 KB  conda-forge
[00:02:07]     setuptools-40.4.3          |           py37_0         574 KB  conda-forge
[00:02:07]     win_inet_pton-1.0.1        |        py37_1002           5 KB  conda-forge
[00:02:07]     wincertstore-0.2           |        py37_1002          13 KB  conda-forge
[00:02:07]     conda-4.5.11               |        py37_1000         654 KB  conda-forge
[00:02:07]     idna-2.7                   |        py37_1002          99 KB  conda-forge
[00:02:07]     conda-env-2.6.0            |                1           2 KB  conda-forge
[00:02:07]     vc-14                      |                0          985 B  conda-forge
[00:02:07]     ruamel_yaml-0.15.71        |py37hfa6e2cd_1000         271 KB  conda-forge
[00:02:07]     pip-18.1                   |        py37_1000         1.8 MB  conda-forge
[00:02:07]     pysocks-1.6.8              |        py37_1002          22 KB  conda-forge
[00:02:07]     vs2015_runtime-14.0.25420  |                0         1.9 MB  conda-forge
[00:02:07]     wheel-0.32.2               |           py37_0          51 KB  conda-forge
[00:02:07]     cffi-1.11.5                |py37hfa6e2cd_1001         212 KB  conda-forge
[00:02:07]     six-1.11.0                 |        py37_1001          21 KB  conda-forge
[00:02:07]     requests-2.20.0            |        py37_1000          83 KB  conda-forge
[00:02:07]     urllib3-1.23               |        py37_1001         151 KB  conda-forge
[00:02:07]     pywin32-223                |py37hfa6e2cd_1000         6.8 MB  conda-forge
[00:02:07]     pycosat-0.6.3              |py37hfa6e2cd_1001          98 KB  conda-forge
[00:02:07]     chardet-3.0.4              |        py37_1003         184 KB  conda-forge
[00:02:07]     python-3.7.0               |    hc182675_1005        21.0 MB  conda-forge
[00:02:07]     openssl-1.0.2p             |    hfa6e2cd_1001         5.4 MB  conda-forge
[00:02:07]     cryptography-2.3.1         |py37h74b6da3_1000         506 KB  conda-forge
[00:02:07]     pyopenssl-18.0.0           |        py37_1000          80 KB  conda-forge
[00:02:07]     pycparser-2.19             |             py_0          87 KB  conda-forge
[00:02:07]     menuinst-1.4.14            |        py37_1000          93 KB  conda-forge
[00:02:07]     asn1crypto-0.24.0          |        py37_1003         154 KB  conda-forge
[00:02:07]     certifi-2018.10.15         |        py37_1000         137 KB  conda-forge
[00:02:07]     ca-certificates-2018.10.15 |       ha4d7672_0         170 KB  conda-forge
[00:02:07]     ------------------------------------------------------------
[00:02:07]                                            Total:        40.5 MB
[00:02:07] 
[00:02:07] The following packages will be UPDATED:
[00:02:07] 
[00:02:07]     asn1crypto:      0.24.0-py37_0          --> 0.24.0-py37_1003          conda-forge
[00:02:07]     ca-certificates: 2018.03.07-0           --> 2018.10.15-ha4d7672_0     conda-forge
[00:02:07]     certifi:         2018.8.24-py37_1       --> 2018.10.15-py37_1000      conda-forge
[00:02:07]     cffi:            1.11.5-py37h74b6da3_1  --> 1.11.5-py37hfa6e2cd_1001  conda-forge
[00:02:07]     chardet:         3.0.4-py37_1           --> 3.0.4-py37_1003           conda-forge
[00:02:07]     conda:           4.5.11-py37_0          --> 4.5.11-py37_1000          conda-forge
[00:02:07]     conda-env:       2.6.0-1                --> 2.6.0-1                   conda-forge
[00:02:07]     cryptography:    2.3.1-py37h74b6da3_0   --> 2.3.1-py37h74b6da3_1000   conda-forge
[00:02:07]     idna:            2.7-py37_0             --> 2.7-py37_1002             conda-forge
[00:02:07]     menuinst:        1.4.14-py37hfa6e2cd_0  --> 1.4.14-py37_1000          conda-forge
[00:02:07]     openssl:         1.0.2p-hfa6e2cd_0      --> 1.0.2p-hfa6e2cd_1001      conda-forge
[00:02:07]     pip:             10.0.1-py37_0          --> 18.1-py37_1000            conda-forge
[00:02:07]     pycosat:         0.6.3-py37hfa6e2cd_0   --> 0.6.3-py37hfa6e2cd_1001   conda-forge
[00:02:07]     pycparser:       2.18-py37_1            --> 2.19-py_0                 conda-forge
[00:02:07]     pyopenssl:       18.0.0-py37_0          --> 18.0.0-py37_1000          conda-forge
[00:02:07]     pysocks:         1.6.8-py37_0           --> 1.6.8-py37_1002           conda-forge
[00:02:07]     python:          3.7.0-hea74fb7_0       --> 3.7.0-hc182675_1005       conda-forge
[00:02:07]     pywin32:         223-py37hfa6e2cd_1     --> 223-py37hfa6e2cd_1000     conda-forge
[00:02:07]     requests:        2.19.1-py37_0          --> 2.20.0-py37_1000          conda-forge
[00:02:07]     ruamel_yaml:     0.15.46-py37hfa6e2cd_0 --> 0.15.71-py37hfa6e2cd_1000 conda-forge
[00:02:07]     setuptools:      40.2.0-py37_0          --> 40.4.3-py37_0             conda-forge
[00:02:07]     six:             1.11.0-py37_1          --> 1.11.0-py37_1001          conda-forge
[00:02:07]     urllib3:         1.23-py37_0            --> 1.23-py37_1001            conda-forge
[00:02:07]     vs2015_runtime:  14.0.25123-3           --> 14.0.25420-0              conda-forge
[00:02:07]     wheel:           0.31.1-py37_0          --> 0.32.2-py37_0             conda-forge
[00:02:07]     win_inet_pton:   1.0.1-py37_1           --> 1.0.1-py37_1002           conda-forge
[00:02:07]     wincertstore:    0.2-py37_0             --> 0.2-py37_1002             conda-forge
[00:02:07] 
[00:02:07] The following packages will be DOWNGRADED:
[00:02:07] 
[00:02:07]     vc:              14-h0510ff6_3          --> 14-0                      conda-forge
[00:02:07]     yaml:            0.1.7-hc54c509_2       --> 0.1.7-vc14_0              conda-forge [vc14]
[00:02:07] 
[00:02:07] Preparing transaction: ...working... done
[00:02:15] Verifying transaction: ...working... done
[00:02:32] Executing transaction: ...working... done
[00:07:06] conda update -q conda
[00:07:15] Solving environment: ...working... done
[00:07:16] 
[00:07:16] # All requested packages already installed.
[00:07:16] 
[00:07:16] conda info -a
[00:07:17] 
[00:07:17]      active environment : None
[00:07:17]        user config file : C:\Users\appveyor\.condarc
[00:07:17]  populated config files : C:\Users\appveyor\.condarc
[00:07:17]           conda version : 4.5.11
[00:07:17]     conda-build version : not installed
[00:07:17]          python version : 3.7.0.final.0
[00:07:17]        base environment : C:\Python36-conda64  (writable)
[00:07:17]            channel URLs : https://conda.anaconda.org/conda-forge/win-64
[00:07:17]                           https://conda.anaconda.org/conda-forge/noarch
[00:07:17]                           https://repo.anaconda.com/pkgs/main/win-64
[00:07:17]                           https://repo.anaconda.com/pkgs/main/noarch
[00:07:17]                           https://repo.anaconda.com/pkgs/free/win-64
[00:07:17]                           https://repo.anaconda.com/pkgs/free/noarch
[00:07:17]                           https://repo.anaconda.com/pkgs/r/win-64
[00:07:17]                           https://repo.anaconda.com/pkgs/r/noarch
[00:07:17]                           https://repo.anaconda.com/pkgs/pro/win-64
[00:07:17]                           https://repo.anaconda.com/pkgs/pro/noarch
[00:07:17]                           https://repo.anaconda.com/pkgs/msys2/win-64
[00:07:17]                           https://repo.anaconda.com/pkgs/msys2/noarch
[00:07:17]           package cache : C:\Python36-conda64\pkgs
[00:07:17]                           C:\Users\appveyor\AppData\Local\conda\conda\pkgs
[00:07:17]        envs directories : C:\Python36-conda64\envs
[00:07:17]                           C:\Users\appveyor\AppData\Local\conda\conda\envs
[00:07:17]                           C:\Users\appveyor\.conda\envs
[00:07:17]                platform : win-64
[00:07:17]              user-agent : conda/4.5.11 requests/2.20.0 CPython/3.7.0 Windows/2012ServerR2 Windows/6.3.9600
[00:07:17]           administrator : True
[00:07:17]              netrc file : None
[00:07:17]            offline mode : False
[00:07:17] 
[00:07:17] # conda environments:
[00:07:17] #
[00:07:17] base                  *  C:\Python36-conda64
[00:07:17] 
[00:07:17] sys.version: 3.7.0 | packaged by conda-forge | (defau...
[00:07:17] sys.prefix: C:\Python36-conda64
[00:07:17] sys.executable: C:\Python36-conda64\python.exe
[00:07:17] conda location: C:\Python36-conda64\lib\site-packages\conda
[00:07:17] conda-build: None
[00:07:17] conda-env: C:\Python36-conda64\Scripts\conda-env.exe
[00:07:17] user site dirs: 
[00:07:17] 
[00:07:17] APR_ICONV_PATH: C:\Program Files (x86)\Subversion\iconv
[00:07:17] CIO_TEST: <not set>
[00:07:17] CONDA_BUILD_PY: 3.6
[00:07:17] CONDA_ROOT: C:\Python36-conda64
[00:07:17] GIT_LFS_PATH: C:\Program Files\Git LFS
[00:07:17] HOMEPATH: \Users\appveyor
[00:07:17] PATH: C:\Python36-conda64;C:\Python36-conda64\Scripts;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Perl\site\bin;C:\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\7-Zip;C:\Program Files\Microsoft\Web Platform Installer\;C:\Tools\GitVersion;C:\Tools\PsTools;C:\Program Files\Git LFS;C:\Program Files (x86)\Subversion\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Tools\WebDriver;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4\;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Ruby193\bin;C:\Tools\NUnit\bin;C:\Tools\xUnit;C:\Tools\MSpec;C:\Tools\Coverity\bin;C:\Program Files (x86)\CMake\bin;C:\go\bin;C:\Program Files\Java\jdk1.8.0\bin;C:\Python27;C:\Program Files\nodejs;C:\Program Files (x86)\iojs;C:\Program Files\iojs;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\MSBuild\14.0\Bin;C:\Tools\NuGet;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Apache\Maven\bin;C:\Python27\Scripts;C:\Tools\NUnit3;C:\Program Files\Mercurial\;C:\Program Files\dotnet\;C:\Tools\curl\bin;C:\Program Files\Amazon\AWSCLI\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\140;C:\Tools\vcpkg;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\erl9.2\bin;C:\Program Files (x86)\NSIS;C:\Tools\Octopus;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\LLVM\bin;C:\Program Files (x86)\Yarn\bin\;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\PowerShell\6\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\nodejs\;C:\Users\appveyor\.dotnet\tools;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\AppVeyor\BuildAgent\;C:\Python36-conda64\lib\site-packages\pywin32_system32
[00:07:17] PSMODULEPATH: C:\Users\appveyor\Documents\WindowsPowerShell\Modules;C:\Users\appveyor\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\PowerShell\Modules;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules;C:\Program Files\AppVeyor\BuildAgent\Modules;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules;C:\Program Files (x86)\AWS Tools\PowerShell;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\Storage;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules;c:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\
[00:07:17] PYTHON: C:\Python36-conda64
[00:07:17] PYTHON_ARCH: 64
[00:07:17] PYTHON_VERSION: 3.6
[00:07:17] REQUESTS_CA_BUNDLE: <not set>
[00:07:17] SSL_CERT_FILE: <not set>
[00:07:17] 
[00:07:17] 
[00:07:17] WARNING: could not import _license.show_info
[00:07:17] # try:
[00:07:17] # $ conda install -n root _license
[00:07:17] conda install -q conda-build conda-verify anaconda-client ca-certificates
[00:07:32] Solving environment: ...working... done
[00:07:44] 
[00:07:44] ## Package Plan ##
[00:07:44] 
[00:07:44]   environment location: C:\Python36-conda64
[00:07:44] 
[00:07:44]   added / updated specs: 
[00:07:44]     - anaconda-client
[00:07:44]     - ca-certificates
[00:07:44]     - conda-build
[00:07:44]     - conda-verify
[00:07:44] 
[00:07:44] 
[00:07:44] The following packages will be downloaded:
[00:07:44] 
[00:07:44]     package                    |            build
[00:07:44]     ---------------------------|-----------------
[00:07:44]     conda-build-3.16.1         |           py37_0         482 KB  conda-forge
[00:07:44]     tqdm-4.28.1                |             py_0          38 KB  conda-forge
[00:07:44]     anaconda-client-1.7.1      |             py_0          66 KB  conda-forge
[00:07:44]     beautifulsoup4-4.6.3       |        py37_1000         141 KB  conda-forge
[00:07:44]     jupyter_core-4.4.0         |             py_0          44 KB  conda-forge
[00:07:44]     pytz-2018.5                |             py_0         193 KB  conda-forge
[00:07:44]     markupsafe-1.0             |py37hfa6e2cd_1001          26 KB  conda-forge
[00:07:44]     click-7.0                  |             py_0          61 KB  conda-forge
[00:07:44]     ipython_genutils-0.2.0     |             py_1          21 KB  conda-forge
[00:07:44]     filelock-3.0.9             |             py_0           9 KB  conda-forge
[00:07:44]     python-libarchive-c-2.8    |        py37_1003          21 KB  conda-forge
[00:07:44]     clyent-1.2.2               |             py_1           9 KB  conda-forge
[00:07:44]     zlib-1.2.11                |           vc14_0         119 KB  conda-forge
[00:07:44]     pyyaml-3.13                |py37hfa6e2cd_1001         147 KB  conda-forge
[00:07:44]     libiconv-1.14              |           vc14_4         670 KB  conda-forge
[00:07:44]     nbformat-4.4.0             |             py_1          91 KB  conda-forge
[00:07:44]     xz-5.2.4                   |    h2fa13f4_1001         805 KB  conda-forge
[00:07:44]     libxml2-2.9.5              |           vc14_1         3.2 MB  conda-forge
[00:07:44]     bzip2-1.0.6                |           vc14_1         144 KB  conda-forge
[00:07:44]     conda-verify-3.1.1         |        py37_1000          49 KB  conda-forge
[00:07:44]     jsonschema-2.6.0           |        py37_1002          80 KB  conda-forge
[00:07:44]     jinja2-2.10                |             py_1          89 KB  conda-forge
[00:07:44]     traitlets-4.3.2            |        py37_1000         130 KB  conda-forge
[00:07:44]     lzo-2.10                   |           vc14_0         154 KB  conda-forge
[00:07:44]     decorator-4.3.0            |             py_0          10 KB  conda-forge
[00:07:44]     pkginfo-1.4.2              |             py_1          19 KB  conda-forge
[00:07:44]     glob2-0.6                  |             py_0          10 KB  conda-forge
[00:07:44]     libarchive-3.3.2           |       h1d0d21d_1         4.0 MB
[00:07:44]     future-0.16.0              |        py37_1002         692 KB  conda-forge
[00:07:44]     psutil-5.4.7               |py37hfa6e2cd_1001         324 KB  conda-forge
[00:07:44]     python-dateutil-2.7.3      |             py_0         202 KB  conda-forge
[00:07:44]     lz4-c-1.8.2                |           vc14_0         254 KB  conda-forge
[00:07:44]     ------------------------------------------------------------
[00:07:44]                                            Total:        12.1 MB
[00:07:44] 
[00:07:44] The following NEW packages will be INSTALLED:
[00:07:44] 
[00:07:44]     anaconda-client:     1.7.1-py_0              conda-forge
[00:07:44]     beautifulsoup4:      4.6.3-py37_1000         conda-forge
[00:07:44]     bzip2:               1.0.6-vc14_1            conda-forge [vc14]
[00:07:44]     click:               7.0-py_0                conda-forge
[00:07:44]     clyent:              1.2.2-py_1              conda-forge
[00:07:44]     conda-build:         3.16.1-py37_0           conda-forge
[00:07:44]     conda-verify:        3.1.1-py37_1000         conda-forge
[00:07:44]     decorator:           4.3.0-py_0              conda-forge
[00:07:44]     filelock:            3.0.9-py_0              conda-forge
[00:07:44]     future:              0.16.0-py37_1002        conda-forge
[00:07:44]     glob2:               0.6-py_0                conda-forge
[00:07:44]     ipython_genutils:    0.2.0-py_1              conda-forge
[00:07:44]     jinja2:              2.10-py_1               conda-forge
[00:07:44]     jsonschema:          2.6.0-py37_1002         conda-forge
[00:07:44]     jupyter_core:        4.4.0-py_0              conda-forge
[00:07:44]     libarchive:          3.3.2-h1d0d21d_1                   
[00:07:44]     libiconv:            1.14-vc14_4             conda-forge [vc14]
[00:07:44]     libxml2:             2.9.5-vc14_1            conda-forge [vc14]
[00:07:44]     lz4-c:               1.8.2-vc14_0            conda-forge [vc14]
[00:07:44]     lzo:                 2.10-vc14_0             conda-forge [vc14]
[00:07:44]     markupsafe:          1.0-py37hfa6e2cd_1001   conda-forge
[00:07:44]     nbformat:            4.4.0-py_1              conda-forge
[00:07:44]     pkginfo:             1.4.2-py_1              conda-forge
[00:07:44]     psutil:              5.4.7-py37hfa6e2cd_1001 conda-forge
[00:07:44]     python-dateutil:     2.7.3-py_0              conda-forge
[00:07:44]     python-libarchive-c: 2.8-py37_1003           conda-forge
[00:07:44]     pytz:                2018.5-py_0             conda-forge
[00:07:44]     pyyaml:              3.13-py37hfa6e2cd_1001  conda-forge
[00:07:44]     tqdm:                4.28.1-py_0             conda-forge
[00:07:44]     traitlets:           4.3.2-py37_1000         conda-forge
[00:07:44]     xz:                  5.2.4-h2fa13f4_1001     conda-forge
[00:07:44]     zlib:                1.2.11-vc14_0           conda-forge [vc14]
[00:07:44] 
[00:07:45] Preparing transaction: ...working... done
[00:07:46] Verifying transaction: ...working... done
[00:08:03] Executing transaction: ...working... done
[00:08:04] SET MPLBACKEND=agg
[00:08:04] .\build\build.cmd -q || exit -1
[00:08:05] Traceback (most recent call last):
[00:08:05]   File "C:\Python36-conda64\Scripts\conda-build-script.py", line 6, in <module>
[00:08:05]     from conda_build.cli.main_build import main
[00:08:05]   File "C:\Python36-conda64\lib\site-packages\conda_build\cli\main_build.py", line 18, in <module>
[00:08:05]     import conda_build.api as api
[00:08:05]   File "C:\Python36-conda64\lib\site-packages\conda_build\api.py", line 22, in <module>
[00:08:05]     from conda_build.config import Config, get_or_merge_config, DEFAULT_PREFIX_LENGTH as _prefix_length
[00:08:05]   File "C:\Python36-conda64\lib\site-packages\conda_build\config.py", line 17, in <module>
[00:08:05]     from .variants import get_default_variant
[00:08:05]   File "C:\Python36-conda64\lib\site-packages\conda_build\variants.py", line 15, in <module>
[00:08:05]     from conda_build.utils import ensure_list, trim_empty_keys, get_logger
[00:08:05]   File "C:\Python36-conda64\lib\site-packages\conda_build\utils.py", line 10, in <module>
[00:08:05]     import libarchive
[00:08:05]   File "C:\Python36-conda64\lib\site-packages\libarchive\__init__.py", line 1, in <module>
[00:08:05]     from .entry import ArchiveEntry
[00:08:05]   File "C:\Python36-conda64\lib\site-packages\libarchive\entry.py", line 6, in <module>
[00:08:05]     from . import ffi
[00:08:05]   File "C:\Python36-conda64\lib\site-packages\libarchive\ffi.py", line 27, in <module>
[00:08:05]     libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
[00:08:05]   File "C:\Python36-conda64\lib\ctypes\__init__.py", line 434, in LoadLibrary
[00:08:05]     return self._dlltype(name)
[00:08:05]   File "C:\Python36-conda64\lib\ctypes\__init__.py", line 356, in __init__
[00:08:05]     self._handle = _dlopen(self._name, mode)
[00:08:05] TypeError: LoadLibrary() argument 1 must be str, not None
[00:08:05] Command exited with code -1
```

For some reason, it installs everything correctly from conda-forge, except for libarchive, which I guess ultimately results in the failed load Library call. I looked into the anaconda repo, and since a good two weeks there is a windows version of libarchive, which roughly matches up with the timeframe of our builds having those issues.

**Comment by pkgw** [comment]
Installing the conda-forge version of libarchive doesn't fix the `LoadLibrary` problem for me. Has anyone made any progress on this?

**Comment by snowman2** [comment]
I am having the same issue: https://github.com/corteva/rioxarray/issues/13

**Comment by jakirkham** [comment]
Not seeing this issue with [recent builds of `libarchive`]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=507874&view=logs&jobId=171a126d-c574-5c8c-1269-ff3b989e923d&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=b5c76c08-4f10-5244-840d-58e98b91712a ). So think this was resolved with along other issues
